# Generated by Django 3.2.5 on 2024-06-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0005_alter_book_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
