# Generated by Django 3.2.5 on 2024-06-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0007_auto_20240613_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
