# Generated by Django 3.2.5 on 2024-06-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0008_auto_20240613_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
