# Generated by Django 3.2.5 on 2024-06-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0009_alter_book_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(default='https://static-01.daraz.pk/p/9c4bbb21ac32475a2f3d8c55d2b7337d.jpg', max_length=255, null=True),
        ),
    ]
