# Generated by Django 3.2.5 on 2024-06-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0010_alter_book_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
